# Orange Pi Zero 2W (Allwinner H618) 极简内核配置 spec
# 用法: bash scripts/wsl-10-minimize-config.sh
!OFF DRM_
!OFF VIDEO_
!OFF SND_
!OFF SOUND_
!OFF HID_
!OFF USB_
!OFF I2C_
!OFF SPI_
!OFF PINCTRL_
!OFF CLK_
!OFF RESET_
!OFF PHY_
!OFF REGULATOR_
!OFF MFD_
!OFF RTC_DRV_
!OFF GPIO_
!OFF SENSORS_
!OFF NVMEM_
!OFF THERMAL_
!OFF WATCHDOG_
!OFF HWSPINLOCK_
!OFF MAILBOX_
!OFF INTERCONNECT_
!OFF IOMMU_
!OFF SERIAL_8250_
!OFF MTD_
!OFF MMC_
!OFF STAGING_
!OFF IIO_
!OFF RMI4_
!OFF KEYBOARD_
!OFF MOUSE_
!OFF TOUCHSCREEN_
!OFF INPUT_TABLET
!OFF INPUT_JOYSTICK
!OFF SERIO_
!OFF PARPORT_
!OFF PCMCIA_
!OFF ISA_
!OFF EISA_
!OFF MCA_
!OFF FB_
!OFF BACKLIGHT_
!OFF LEDS_
!OFF TMIO_
!OFF UIO_
!OFF ANDROID_
!OFF VHOST_
!OFF CAN_
!OFF ISDN_
!OFF WAN_
!OFF HAMRADIO_
!OFF IEEE802154_
!OFF WIMAX_
!OFF MHI_
!OFF RPMSG_
!OFF GREYFS_
!OFF NET_DSA
!OFF DSA_
!OFF SWITCH_
!OFF PTP_
!OFF MDIO_
!OFF WILINK_
!OFF RTLWIFI_
!OFF RTL8188_
!OFF RTL8192_
!OFF MT76_
!OFF MT7621_
!OFF ATH_
!OFF IWLMVT
!OFF RTW_
!OFF VIRTIO_
!OFF XEN_
!OFF HYPERV_
!OFF PVPANIC_
!OFF QCOM_
!OFF MEDIATEK_
!OFF ROCKCHIP_
!OFF MVEBU_
!OFF MESON_
!OFF AMLOGIC_
!OFF IMX_
!OFF MXS_
!OFF TI_
!OFF OMAP_
!OFF EXYNOS_
!OFF SAMSUNG_
!OFF TEGRA_
!OFF BCM_
!OFF BCMIPROC_
!OFF BRCMSTB_
!OFF SUN4I_
!OFF SUN5I_
!OFF SUN6I_
!OFF SUN7I_
!OFF SUN8I_
!OFF SUN9I_
!OFF SUN50I_
!OFF ALLWINNER_
!OFF SUNXI
!OFF AXP_
!OFF AC100_
!OFF AC200_
!OFF HANTRO_
!OFF CEDAR_
!OFF CEDARC
!OFF VMEM_
!OFF VM_REMOTE_
!OFF UDISK_
!OFF LOGO_
!OFF NLS_
!OFF EXT2_FS
!OFF F2FS_
!OFF HFS_
!OFF HFSPLUS_
!OFF AFFS_FS
!OFF BEFS_FS
!OFF ECRYPT_FS
!OFF JFS_FS
!OFF JFFS2_
!OFF UBIFS_FS
!OFF UDF_FS
!OFF UFS_FS
!OFF VXFS_FS
!OFF OCFS2_
!OFF REISERFS_FS
!OFF NILFS2_
!OFF SQUASHFS_
!OFF ZONEFS_FS
!OFF HOSTFS_FS
!OFF RAID6_
!OFF RAID456_
!OFF BLK_DEV_RAM
!OFF BLK_DEV_DM
!OFF DM_VERITY
!OFF DM_CRYPT
!OFF DVB_
!OFF MEDIA_SUBSYS_
!OFF MEDIA_USB_
!OFF MEDIA_PCI_
ARCH_SUNXI=y
BLOCK=y
MODULES=y
MMU=y
SMP=y
NR_CPUS=4
OF=y
OF_OVERLAY=y
OF_DYNAMIC=y
OF_EARLY_FLATTREE=y
EXPERIMENTAL=y
COMPILE_TEST=n
GPIOLIB=y
GPIO_SYSFS=y
GPIO_CDEV=y
OF_GPIO=y
GPIO_GENERIC=y
PINCTRL=y
COMMON_CLK=y
RESET_CONTROLLER=y
MTD=y
MMC=y
I2C=y
I2C_BOARDINFO=y
SPI=y
SPI_MASTER=y
PHYLIB=y
MDIO_DEVICE=y
MDIO_BUS=y
MEDIA_SUPPORT=y
MEDIA_SUPPORT_FILTER=y
MEDIA_PLATFORM_DRIVERS=y
V4L_PLATFORM_DRIVERS=y
V4L_MEM2MEM_DRIVERS=y
VIDEO_DEV=y
RC_CORE=y
SOUND=y
SND=y
SND_PCM=y
SND_HWDEP=y
SND_RAWMIDI=n
SND_TIMER=y
SND_HRTIMER=y
SND_DYNAMIC_MINORS=n
SND_OSSEMUL=n
SND_SEQUENCER=n
SND_MIXER_OSS=n
SND_PCM_OSS=n
SND_USB=n
SND_HDA=n
SND_HDA_INTEL=n
SND_SOC=y
SND_ARM=y
DRM=y
DRM_KMS_HELPER=y
DRM_KMS_FBDEV=n
DRM_PANEL=y
DRM_BRIDGES=y
USB_SUPPORT=y
USB=y
USB_COMMON=y
USB_HOST_COMMON=y
USB_XHCI_HCD=n
USB_XHCI_PLATFORM=n
USB_EHCI_HCD=y
USB_OHCI_HCD=y
USB_HID=y
HID=y
HID_GENERIC=y
HID_SENSOR_HUB=n
INPUT=y
INPUT_MOUSE=n
INPUT_TOUCHSCREEN=n
INPUT_TABLET=n
NEW_LEDS=y
LEDS_CLASS=y
RTC_LIB=y
I2C_CHARDEV=y
IIO=y
IIO_BUFFER=n
IIO_KFIFO_BUF=n
WATCHDOG=y
WATCHDOG_CORE=y
NVMEM=y
NVMEM_SYSFS=y
THERMAL=y
THERMAL_OF=y
THERMAL_HWMON=y
REGULATOR=y
PINCTRL_SUNXI=y
PINCTRL_SUN50I_H616=y
PINCTRL_SUN50I_H616_R=y
GPIO_SUNXI=y
SUNXI_CCU=y
SUN50I_H616_CCU=y
SUN50I_H6_R_CCU=y
SUN6I_A31_R_CCU=y
SUNXI_RSB=y
SUNXI_SRAM=y
SUNXI_SYSCONFIG=y
SUNXI_MBUS=y
SUN50I_IOMMU=y
IOMMU_SUPPORT=y
IOMMU_IO_PGTABLE_LPAE=y
RESET_SUNXI=y
SUN6I_R_INTC=y
SUNXI_NMI_INTC=y
HWSPINLOCK=y
HWSPINLOCK_SUN6I=y
SUN6I_MSGBOX=y
SUNXI_WATCHDOG=y
SUNXI_SYS_INFO=y
NVMEM_SUNXI_SID=y
# UWE5622 vendor WLAN expects the Allwinner MAC-address provider used by the
# official Zero 2W configuration.
SUNXI_ADDR_MGT=m
SUNXI_DMA=y
DMADEVICES=y
DMA_ENGINE=y
DMA_VIRTUAL_CHANNELS=y
SUN8I_THERMAL=y
SUNXI_EFUSE=y
SUNXI_GPIOD=y
SUNXI_PRCM=y
POWER_SUPPLY=y
REGULATOR_AXP20X=y
REGULATOR_FIXED_VOLTAGE=y
REGULATOR_GPIO=y
REGULATOR_SUNXI=n
MFD_CORE=y
MFD_AXP20X=y
MFD_AXP20X_RSB=y
MFD_AXP20X_I2C=y
MFD_SUN6I_PRCM=y
MFD_AC200=y
AC200_OTG=y
AC200_RSTI=y
AC200_MCU=y
AC200_EMAC=y
AC200_RTC=y
AC200_CODEC=y
AC200_ADC=y
AC200_PWM=y
AC200_LED=y
AC200_USB=y
AC200_CHRGT=y
AC200_TEMP=y
AC200_REGULATOR=y
AC200_IRQ=y
AC200_POWEROFF=y
CPU_FREQ=y
CPU_FREQ_STAT=n
CPU_FREQ_DT=y
CPU_FREQ_OF=y
CPU_FREQ_GOV_PERFORMANCE=y
CPU_FREQ_GOV_POWERSAVE=y
CPU_FREQ_GOV_ONDEMAND=y
CPU_FREQ_GOV_CONSERVATIVE=y
CPU_FREQ_GOV_SCHEDUTIL=y
CPU_FREQ_DEFAULT_GOV_ONDEMAND=y
ARM_ALLWINNER_SUN50I_CPUFREQ_NVMEM=y
CPU_IDLE=y
ARM_CPUIDLE=y
ARM_PSCI_CPUIDLE=y
CPU_IDLE_MULTIPLE_DRIVERS=n
CPU_IDLE_GOV_MENU=y
RTC_CLASS=y
RTC_DRV_SUN6I=y
RTC_INTF_DEV=y
RTC_DRV_SUNXI=n
KEYBOARD_GPIO=y
KEYBOARD_SUN4I_LRADC=y
INPUT_KEYBOARD=y
INPUT_EVDEV=y
LEDS_GPIO=y
LEDS_TRIGGER=y
LEDS_TRIGGER_HEARTBEAT=y
LEDS_TRIGGER_NETDEV=y
LEDS_TRIGGER_GPIO=y
LEDS_TRIGGER_TIMER=y
LEDS_TRIGGER_DEFAULT_ON=y
IR_SUNXI=y
IR_PROTOCOL_DECODERS=y
RC_DECODERS=y
RC_DEVICES=y
RC_LOOPBACK=n
RC_ATI_REMOTE=n
LIRC=y
SUNXI_CSI2=y
SUNXI_VIN=n
SUN50I_DE2_BUS=y
DRM_SUN4I=y
DRM_SUN4I_BACKEND=y
DRM_SUN8I_MIXER=y
DRM_SUN8I_TCON_TOP=y
DRM_SUN8I_DW_HDMI=y
DRM_SUN4I_HDMI=y
DRM_SUN4I_HDMI_CEC=y
DRM_DW_HDMI=y
DRM_DW_HDMI_I2S_AUDIO=y
DRM_DW_HDMI_CEC=y
CEC_CORE=y
CEC_SUNXI_SED=y
DRM_PANFROST=y
DRM_GPU_VM_MANAGEMENT=y
DRM_FBDEV_EMULATION=y
DRM_FBDEV_OVERALLOC=100
FB_CORE=y
FB_DEFERRED_IO=n
STAGING_MEDIA=y
VIDEO_SUNXI=y
VIDEO_SUNXI_CEDRUS=y
V4L2_MEM2MEM_DEV=y
VIDEO_V4L2_SUBDEV_API=y
MEDIA_CONTROLLER=y
MEDIA_REQUEST=y
MEDIA_TEST_SUPPORT=n
VIDEO_V4L2_REQUESTS=y
SUNXI_VE_UTILS=y
SND_SUN50IW9_CODEC=y
SND_SOC_SUN50IW9_CODEC=y
SND_SUN50I_CODEC_ANALOG=y
SND_SOC_SUNXI_MACH=y
SND_SOC_SUNXI_AHUB=y
SND_SOC_SUNXI_AHUB_DAM=y
SND_SOC_SUNXI_INTERNALCODEC=y
SND_SOC_SUNXI_AAUDIO=y
SND_SOC_SUNXI_HDMICODEC=y
SND_SOC_HDMI_CODEC=y
SND_SOC_AW8738=y
SND_SOC_SPDIF=y
SND_SOC_SUN50I_DMIC=m
SND_SOC_GENERIC_DMAENGINE_PCM=y
SND_SOC_SUNXI_PCM=y
SND_SOC_SUNXI_I2S=y
WLAN=y
WLAN_VENDOR_BROADCOM=y
WLAN_VENDOR_ADMTEK=n
BRCMUTIL=y
BRCMFMAC=y
BRCMFMAC_SDIO=y
BRCMFMAC_PROTO_BCDC=y
BRCMFMAC_PROTO_MSFT_ICS=y
BRCMFMAC_DEBUGFS=n
MAC80211=y
MAC80211_HAS_RC=y
MAC80211_RC_MINSTREL=y
MAC80211_RC_DEFAULT_MINSTREL=y
MAC80211_RC_DEFAULT="minstrel_ht"
MAC80211_MESH=n
MAC80211_LEDS=y
MAC80211_DEBUGFS=n
CFG80211=y
CFG80211_WEXT=y
CFG80211_CRDA_SUPPORT=y
CFG80211_DEBUGFS=n
WIRELESS=y
WIRELESS_EXT=y
WEXT=y
WEXT_CORE=y
WEXT_PROC=n
WEXT_SPY=n
WEXT_PRIV=n
WIRELESS_EXT_SYSFS=n
RFKILL=y
RFKILL_INPUT=y
BT=y
BT_BCM=y
BT_HCIUART=y
BT_HCIUART_BCM=y
BT_HCIUART_H4=y
BT_HCIUART_SERDEV=y
BT_HCIUART_RTK=n
BT_HCIUART_ATH3K=n
BT_HCIUART_LL=n
BT_HCIUART_3W=n
BT_HCIUART_INTEL=n
BT_HCIUART_QCA=n
BT_HCIUART_AG6XX=n
BT_HCIUART_MRVL=n
BT_HCIUART_NOKIA=n
BT_HCIBTUSB=n
BT_HCIBTSDIO=n
BT_HCIBFUSB=n
BT_HCIDTL1=n
BT_HCIBT3C=n
BT_HCIBLUECARD=n
BT_HCIVHCI=n
BT_MRVL=n
BT_INTEL=n
BT_QCA=n
BT_BREDR=y
BT_LE=y
BT_HS=n
BT_6LOWPAN=n
BT_RFCOMM=y
BT_RFCOMM_TTY=y
BT_BNEP=y
BT_BNEP_MC_FILTER=y
BT_BNEP_PROTO_FILTER=y
BT_HIDP=y
BT_FEATURE_DEVICEID=y
NETDEVICES=y
ETHERNET=y
MDIO_SUN4I=y
SUNXI_EPHY_AC200=y
PHY_SUN6I_EPHY=y
SUNXI_GMAC=y
SUN4I_EMAC=y
DWMAC_SUN8I=n
INET=y
IP_MULTICAST=y
IP_ADVANCED_ROUTER=y
IP_MULTIPLE_TABLES=y
IP_ROUTE_MULTIPATH=y
IP_ROUTE_VERBOSE=n
IP_MROUTE=y
IP_MROUTE_MULTIPLE_TABLES=y
IP_PIMSM_V2=y
IP_FIB_LOOKUP=y
IP_PNP=y
IP_PNP_RARP=y
IP_NF_IPTABLES=y
IP_NF_FILTER=y
IP_NF_MANGLE=y
IP_NF_NAT=y
IP_NF_TARGET_MASQUERADE=y
IP_NF_TARGET_REJECT=y
IP_NF_TARGET_REDIRECT=y
IPV6=y
IPV6_SIT=y
IPV6_MULTIPLE_TABLES=y
IPV6_MROUTE=y
IPV6_MROUTE_MULTIPLE_TABLES=y
IPV6_PIMSM_V2=y
IPV6_ROUTER_PREF=y
IPV6_ROUTE_INFO=n
IPV6_TUNNEL=n
IPV6_VTI=n
IPV6_6TO4=n
NETFILTER=y
NETFILTER_ADVANCED=y
NETFILTER_XT=y
NETFILTER_XT_NAT=y
NETFILTER_XT_TARGET_MASQUERADE=y
NETFILTER_XT_TARGET_LOG=y
NETFILTER_XT_MATCH_COMMENT=y
NETFILTER_XT_MATCH_CONNTRACK=y
NETFILTER_XT_MATCH_STATE=y
NETFILTER_XT_MATCH_MULTIPORT=y
NETFILTER_XT_MATCH_ADDRTYPE=y
NF_CONNTRACK=y
NF_CONNTRACK_TIMESTAMP=y
NF_CONNTRACK_NETBIOS_NS=y
NF_CONNTRACK_FTP=y
NF_CONNTRACK_TFTP=y
NF_CONNTRACK_IPV4=y
NF_CONNTRACK_IPV6=y
NF_CONNTRACK_PROTO_GRE=n
NF_CONNTRACK_H323=n
NF_CONNTRACK_SIP=n
NF_CONNTRACK_IRC=n
NF_CONNTRACK_PPTP=n
NF_CONNTRACK_AMANDA=n
NF_CONNTRACK_SANE=n
NF_CONNTRACK_SNMP=n
NF_DEFRAG_IPV4=y
NF_DEFRAG_IPV6=y
NF_NAT=y
NF_NAT_MASQUERADE=y
NF_NAT_REDIRECT=y
NF_NAT_SNMP_BASIC=n
NF_TABLES=y
NF_TABLES_INET=y
NF_TABLES_IPV4=y
NF_TABLES_IPV6=y
NF_TABLES_BRIDGE=y
NF_TABLES_ARP=y
NF_TABLES_NETDEV=y
NFT_CT=y
NFT_LOG=y
NFT_LIMIT=y
NFT_MASQ=y
NFT_REJECT=y
NFT_REJECT_INET=y
NFT_NAT=y
NFT_QUOTA=y
NFT_COMPAT=y
NFT_FIB=y
NFT_FIB_INET=y
NFT_FIB_IPV4=y
NFT_FIB_BRIDGE=y
NFT_CONNLIMIT=y
NFT_QUEUE=n
NFT_LOG_TRACE=n
BRIDGE=y
BRIDGE_IGMP_SNOOPING=y
BRIDGE_NETFILTER=y
VLAN_8021Q=y
PACKET=y
UNIX=y
MPTCP=n
KCP=n
MCTCP=n
L2TP=n
PPP=n
PPPOE=n
PPTP=n
SLIP=n
TIPC=n
ATM=n
AX25=n
NET_FC=n
IEEE802154_SOCKET=n
I2C_MV64XXX=y
I2C_SUN6I_P2P=y
SERIAL_8250=y
SERIAL_8250_CONSOLE=y
SERIAL_8250_NR_UARTS=8
SERIAL_8250_RUNTIME_UARTS=8
SERIAL_8250_EXTENDED=y
SERIAL_8250_MANY_PORTS=y
SERIAL_8250_SHARE_IRQ=y
SERIAL_EARLYCON=y
SERIAL_DEV_BUS=y
SERIAL_DEV_CTRL_TTYPORT=y
TTY=y
TTY_PRINTK=y
HW_CONSOLE=y
VT=y
VT_HW_CONSOLE_BINDING=y
UNIX98_PTYS=y
LEGACY_PTYS=n
MMC_BLOCK=y
MMC_BLOCK_MINORS=16
MMC_SDIO=y
MMC_SDIO_SPARSE=y
MMC_SUNXI=y
MMC_SDHCI=n
MMC_SDHCI_PLTFM=n
MTD_BLOCK=y
MTD_PARTITIONS=y
MTD_OF_PARTS=y
MTD_CMDLINE_PARTS=y
MTD_SPI_NOR=y
MTD_PHYSMAP=n
SPI_SUN4I=y
SPI_SPIDEV=y
SPI_MEM=y
SPI_NOR_4B_OPCODES=y
SPI_SLAVE=y
USB_EHCI_HCD_PLATFORM=y
USB_EHCI_ROOT_HUB_TT=y
USB_EHCI_TT_NEWSCHED=y
USB_OHCI_HCD_PLATFORM=y
USB_MUSB_HDRC=y
USB_MUSB_SUNXI=y
USB_MUSB_DUAL_ROLE=y
USB_MUSB_PIO_ONLY=n
USB_GADGET=y
UDC_CORE=y
USB_LIBCOMPOSITE=y
USB_F_FS=y
USB_CONFIGFS=y
USB_CONFIGFS_F_FS=y
USB_CONFIGFS_RNDIS=y
USB_CONFIGFS_MASS_STORAGE=y
USB_CONFIGFS_ACM=y
USB_FUNCTIONFS=y
USB_FUNCTIONFS_ETH=y
USB_FUNCTIONFS_RNDIS=y
USB_FUNCTIONFS_GENERIC=y
NOP_USB_XCEIV=y
PHY_SUN4I_USB=y
USB_STORAGE=y
USB_STORAGE_DEBUG=n
USB_UAS=y
USB_NET_DRIVER=y
USB_NET_RNDIS_HOST=y
USB_NET_CDCETHER=y
USB_NET_CDC_NCM=n
USB_NET_QMI_WWAN=n
USB_SERIAL=n
USB_G_SERIAL=n
USB_PRINTER=n
USB_CDC_ACM=n
USB_VIDEO_CLASS=n
USB_MEDIA=n
USB_ACCESSORY=n
USB_STORAGE_REALTEK=y
USB_STORAGE_CYPRESS_ATACB=n
USB_STORAGE_ONETOUCH=n
USB_IDMOUSE=n
USB_EMI62=n
USB_GADGET_MUSB_HDRC=y
TMPFS=y
TMPFS_POSIX_ACL=y
TMPFS_XATTR=y
TMPFS_QUOTA=n
EXT4_FS=y
EXT4_USE_FOR_EXT2=y
EXT4_FS_POSIX_ACL=y
EXT4_FS_SECURITY=y
EXT4_DEBUG=n
JBD2=y
MBCACHE=y
FS_IOMAP=y
FS_MBCACHE=y
FAT_FS=y
MSDOS_FS=y
VFAT_FS=y
FAT_DEFAULT_IOCHARSET="utf8"
FAT_DEFAULT_UTF8=y
NLS=y
NLS_CODEPAGE_437=y
NLS_ISO8859_1=y
NLS_ASCII=y
NLS_UTF8=y
OVERLAY_FS=y
FS_POSIX_ACL=y
FS_ENCRYPTION=n
AUTOFS4_FS=n
DAX=n
ZONE_DEVICE=n
BLK_DEV=y
BLK_DEV_BUILTIN=y
BLK_DEV_LOOP=y
BLK_DEV_LOOP_MIN_COUNT=0
BLK_DEV_SD=y
SCSI=y
SCSI_LOWLEVEL=y
SCSI_PROC=n
SCSI_SPI_ATTRIBUTES=n
SCSI_FC_ATTRIBUTES=n
BLK_DEV_NBD=n
BLK_DEV_FD=n
PARTITION_ADVANCED=n
PROC_FS=y
PROC_SYSCTL=y
PROC_PAGE_MONITOR=y
SYSFS=y
KOBJECT_UEVENT=y
UEVENT_HELPER_PATH=""
DEVTMPFS=y
DEVTMPFS_MOUNT=y
CGROUPS=y
CGROUP_SCHED=y
FAIR_GROUP_SCHED=y
CGROUP_PIDS=y
CGROUP_BPF=n
CGROUP_HUGETLB=n
CPUSETS=n
MEMCG=n
BLK_CGROUP=n
IO_CGROUP=y
IO_WQ=y
IO_URING=n
NAMESPACES=y
UTS_NS=y
IPC_NS=y
PID_NS=y
USER_NS=n
NET_NS=y
SYSVIPC=y
POSIX_MQUEUE=y
SIGNALFD=y
TIMERFD=y
EVENTFD=y
EPOLL=y
FHANDLE=y
INOTIFY_USER=y
FILE_LOCK=y
MISC_FILESYSTEMS=y
CRYPTO=y
CRYPTO_ALGAPI=y
CRYPTO_BLG=y
CRYPTO_HASH=y
CRYPTO_SKCIPHER=y
CRYPTO_AEAD=y
CRYPTO_INTERNAL=y
CRYPTO_MANAGER_DISABLE_TESTS=y
CRYPTO_NULL_LAST=y
CRYPTO_AES=y
CRYPTO_AES_ARM=y
CRYPTO_AES_ARM_BS=y
CRYPTO_AES_ARM_CE=y
CRYPTO_ARC4=y
CRYPTO_DES=y
CRYPTO_BLOWFISH=n
CRYPTO_TWOFISH=n
CRYPTO_CAMELLIA=n
CRYPTO_SERPENT=n
CRYPTO_CAST5=n
CRYPTO_XTS=y
CRYPTO_CMAC=y
CRYPTO_MICHAEL_MIC=y
CRYPTO_MD5=y
CRYPTO_SHA1=y
CRYPTO_SHA256=y
CRYPTO_SHA512=y
CRYPTO_HMAC=y
CRYPTO_GHASH=y
CRYPTO_GHASH_ARM_CE=y
CRYPTO_SHA1_ARM=y
CRYPTO_SHA1_ARM_CE=y
CRYPTO_SHA2_ARM_CE=y
CRYPTO_CRC32=y
CRYPTO_CRC32C=y
CRYPTO_CRC32_ARM_CE=y
CRYPTO_LIB_CHACHA=y
CRYPTO_LIB_POLY1305=y
CRYPTO_LIB_CURVES=n
CRYPTO_LIB_MEMNEQ=y
CRYPTO_LIB_DES=y
CRYPTO_LIB_SHA1=y
CRYPTO_LIB_SHA256=y
CRYPTO_LIB_SHA512=y
CRYPTO_LIB_ARC4=y
CRYPTO_LIB_CHACHA_GENERIC=y
CRYPTO_AUTHENC=y
CRYPTO_SEQIV=y
CRYPTO_CTR=y
CRYPTO_CTS=y
CRYPTO_ECB=y
CRYPTO_LRW=n
CRYPTO_PCBC=n
CRYPTO_USER=y
CRYPTO_USER_API=y
CRYPTO_USER_API_HASH=y
CRYPTO_USER_API_SKCIPHER=y
CRYPTO_USER_API_RNG=y
CRYPTO_USER_API_AEAD=y
CRYPTO_CBC=y
CRYPTO_DEV_SUN4I_SS=y
CRYPTO_DEV_SUN8I_CE=y
KEYS=y
TRUSTED_KEYS=n
ENCRYPTED_KEYS=n
ASYNC_CORE=n
EXPERT=y
EMBEDDED=y
BASE_SMALL=1
BASE_FULL=n
# Keep the vendor WLAN stack on its validated -O2 code path. The UWE5622 BSP
# is out-of-tree code and is not reliable under the previous global -Os build.
CC_OPTIMIZE_FOR_SIZE=n
CC_OPTIMIZE_FOR_PERFORMANCE=y
SLUB=y
SLUB_DEBUG=n
SLUB_DEBUG_ON=n
SLAB_FREELIST_RANDOM=n
SLAB_FREELIST_HARDENED=n
SLOB=n
SLOB_DEBUG=n
HZ=100
HZ_100=y
HZ_250=n
HZ_300=n
HZ_1000=n
LOG_BUF_SHIFT=15
LOG_CPU_MAX_BUF_SHIFT=11
LOG_BUF_PAGES=2
PANIC_TIMEOUT=5
LIVEPATCH=n
KALLSYMS=y
KALLSYMS_ALL=n
KALLSYMS_ABSOLUTE_PERCPU=n
KPROBES=n
KPROBE_EVENTS=n
JUMP_LABEL=y
STACKTRACE=n
FUNCTION_TRACER=n
FTRACE=n
IRQ_WORK=n
UPROBES=n
PERF_EVENTS=n
DEBUG_KERNEL=n
DEBUG_INFO=n
DEBUG_INFO_NONE=y
DEBUG_FS=n
DEBUG_MISC=n
PROC_KCORE=n
SCHED_DEBUG=n
SCHED_STACK_END_CHECK=n
SCHED_INFO=n
RCU_TORTURE_TEST=n
LOCK_TORTURE_TEST=n
PROVE_LOCKING=n
PROVE_RCU=n
DEBUG_LIST=n
DEBUG_SG=n
DEBUG_VM=n
FRAME_WARN=0
BUG_VERBOSE_OUTPUT=n
GCOV=n
KCOV=n
KCSAN=n
UBSAN=n
UBSAN_SHIFT=n
REFCOUNT_FULL=n
LIST_HARDENED=n
HARDENED_USERCOPY=n
FORTIFY_SOURCE=n
STACKPROTECTOR=n
STACKPROTECTOR_STRONG=n
STACKPROTECTOR_PER_TASK=n
SHADOW_CALL_STACK=n
# Match the official UWE5622 build contract. Its PM callbacks and SDIO wake
# paths are compiled against CONFIG_PM_SLEEP.
SUSPEND=y
HIBERNATION=n
PM_SLEEP=y
PM_STD=n
ACPI=n
EFI=n
EFI_STUB=n
EFI_VARS=n
KVM=n
VIRTUALIZATION=n
HYPERVISOR_GUEST=n
XEN=n
VIRTIO_MENU=n
VIRTIO_BALLOON=n
VIRTIO_NET=n
BLK_DEV_INITRD=n
RD_GZIP=n
RD_BZIP2=n
RD_LZMA=n
LZO_DECOMPRESS=y
ZSTD_DECOMPRESS=n
DECOMPRESS_LZ4=n
RD_LZ4=n
RD_LZO=n
ZRAM=n
ZSMALLOC=n
KSM=n
IOSCHED_BFQ=n
BFQ_GROUP_IOSCHED=n
MQ_IOSCHED_DEADLINE=y
DEFAULT_MQ_DEADLINE=y
DEFAULT_IOSCHED_MQ_DEADLINE=y
DEFAULT_IOSCHED="mq-deadline"
MODULE_SIG=n
# lockdown LSM 会 select MODULE_SIG -> 整个 LSM 关掉才断得掉
LOCKDOWN=n
SECURITY_LOCKDOWN_LSM=n
SECURITY_LOCKDOWN_LSM_EARLY=n
MODULE_SIG_SHA1=n
ASN1=n
ASN1_ENCODER=n
ASYMMETRIC_KEY_TYPE=n
ASYMMETRIC_PUBLIC_KEY_SUBTYPE=n
X509_CERTIFICATE_PARSER=n
PKCS7_MESSAGE_PARSER=n
PKCS8_PRIVATE_KEY_PARSER=n
SIGNED_PE_FILE_VERIFICATION=n
SYSTEM_TRUSTED_KEYRING=n
SYSTEM_BLACKLIST=n
INTEGRITY_PLATFORM_KEYRING=n
INTEGRITY_MACHINE_KEYRING=n
MODULE_SIG_ALL=n
MODULE_SIG_FORCE=n
MODULE_COMPRESS_NONE=y
MODULE_COMPRESS=n
MODVERSIONS=n
MODULE_UNLOAD=y
DEBUG_SET_MODULE_RONX=n
SET_MODULE_RO_DATA=n
BPF_SYSCALL=n
BPF_JIT=n
BPF_UNPRIV_DEFAULT_OFF=y
BPF_EVENTS=n
BPF_LIRC_MODE2=n
BPF_STREAM_PARSER=n
BPFILTER=n
LIBBPF=n
TRACE_IRQFLAGS=n
TRACE_IRQFLAGS_SUPPORT=n
LOCKUP_DETECTOR=n
BOOTPARAM_TRACENOPRIO=n
WATCHDOG_NOWAYOUT=n
BUG=y
SECCOMP=y
SECCOMP_FILTER=y
VM_EVENT_COUNTERS=n
DEFAULT_MMAP_MIN_ADDR=4096
SPLIT_PTE=n
HIGHMEM=n
VMSPLIT_3=n
PRINTK_NMI=y
CMDLINE="earlyprintk console=ttyS0,115200 loglevel=4 rootwait"
CMDLINE_BOOL=y
CMDLINE_FORCE=n
CAN=n
CAN_RAW=n
CAN_VX_CANIF=n
ISDN=n
WAN=n
HAMRADIO=n
IEEE802154=n
WIMAX=n
MHI=n
RPMSG=n
STAGING=y
SND_SOC_SUNXI_V200_CODEC_AUDIOLINK=n
SUNXI_HDMI_DCDC=n

# ---------- 大块内存预留: CMA / ION (实测最大的一项运行内存开销) ----------
# 原 BSP: CMA_SIZE_MBYTES=128 -> 开机 MemTotal 直接少 128MB(1GB 板的 12.5%)
CMA=y
DMA_CMA=y
CMA_SIZE_MBYTES=16
CMA_SIZE_SEL_MBYTES=y
CMA_ALIGNMENT=8
CMA_AREAS=2
CMA_DEBUGFS=n
CMA_SYSFS=n
ION=n
STAGINGION=n
UIO=n
IOMMU_DEFAULT_DMA_LAZY=y
IOMMU_DEFAULT_DMA_STRICT=n
IOMMU_DEFAULT_PASSTHROUGH=n

# ---------- 加快 probe: 不等待 clock/pmu/regulator 等供应商依赖 ----------
# FW_DEVLINK=n   <- 本树无此符号(6.3+才有), 用内核命令行 fw_devlink=off 代替

# ---------- 签名校验拉进来的 ASN1/X509/PKCS7 栈 ----------
ASN1=n
ASN1_ENCODER=n
ASYMMETRIC_KEY_TYPE=n
ASYMMETRIC_PUBLIC_KEY_SUBTYPE=n
X509_CERTIFICATE_PARSER=n
PKCS7_MESSAGE_PARSER=n
PKCS8_PRIVATE_KEY_PARSER=n
SIGNED_PE_FILE_VERIFICATION=n
SYSTEM_TRUSTED_KEYRING=n
SYSTEM_BLACKLIST_KEYRING=n
INTEGRITY=n
INTEGRITY_PLATFORM_KEYRING=n
INTEGRITY_MACHINE_KEYRING=n
MODULE_SIG=n
# lockdown LSM 会 select MODULE_SIG -> 整个 LSM 关掉才断得掉
LOCKDOWN=n
SECURITY_LOCKDOWN_LSM=n
SECURITY_LOCKDOWN_LSM_EARLY=n

# ---------- 切断 LOCKDOWN -> MODULE_SIG 的 select 链 ----------
MEDIA_SUBDRV_AUTOSELECT=n

# ================== 第三轮补充（审计得出: 板上根本没有的东西） ==================
# 裸符号, 不带下划线, 前缀 !OFF 命中不到
SERIO=n
LOGO=n
UEVENT_HELPER=n
INPUT_MISC=n
INPUT_MOUSEDEV=n
INPUT_UINPUT=n
HUGETLB_PAGE=n
TRANSPARENT_HUGEPAGE=n
THP_SWAP=n
THP_FILE=n
COMPACTION=n
MEMORY_FAILURE=n
CGROUP_FREEZER=n
RELAY=n
IIO_BUFFER=n
IIO_KFIFO_BUF=n
IIO_TRIGGER=n
IIO_TRIGGERS=n
IIO_SW_TRIGGER=n
IIO_EVENT=n
# 板上只有 Cedrus VPU + IR 接收头, 没有任何 TV / Radio / SDR / DVB 设备
MEDIA_DIGITAL_TV_SUPPORT=n
MEDIA_RADIO_SUPPORT=n
MEDIA_SDR_SUPPORT=n
# media 平台驱动菜单必须留着, 否则 IR_SUNXI 和 Cedrus 会一起消失
MEDIA_PLATFORM_SUPPORT=y
V4L_PLATFORM_DRIVERS=y
V4L_TEST_DRIVERS=n
MEDIA_TEST_SUPPORT=n
DVB_NET=n
MEDIA_COMMON_OPTIONS=n
DVB_CORE=n
!OFF MEDIA_TUNER
!OFF DVB_
!OFF RC_
RC_CORE=y
IR_SUNXI=y
IR_PROTOCOL_DECODERS=y
RC_DECODERS=y
RC_DEVICES=y
RC_LOOPBACK=n
RC_ATI_REMOTE=n
# 板上没有的总线与安全芯片: 1-Wire / TPM(TCG) / NFC / TEE / HW RNG
W1=n
BATTERY_DS2780=n
BATTERY_DS2781=n
BATTERY_DS2782=n
BATTERY_BQ27XXX=n
!OFF W1
TCG=n
!OFF TCG
NFC=n
!OFF NFC
TEE=n
!OFF TEE
HW_RANDOM=n
!OFF HW_RANDOM
MHI=n
!OFF MHI
# 网络扩展里 CarPlay 用不到的部分 (只保留 NAT/masq/conntrack/basic filter)
!OFF NET_CLS
!OFF NET_SCH
!OFF NET_EMATCH
!OFF NET_ACT
!OFF NET_IFE
!OFF NET_TEAMS
NET_TEAMS=n
!OFF BRIDGE_EBT
BRIDGE_EBT_BROUTE=n
!OFF IP_VS
IP_VS=n
!OFF IP_SET
IP_SET=n
TCP_CONG_ADVANCED=n
!OFF 6LOWPAN
NET_6LOWPAN=n
!OFF IEEE802154
!OFF AX25
AX25=n
!OFF ROSE
!OFF X25
!OFF NETROM
!OFF PLIP
!OFF SCTP
IP_SCTP=n
!OFF DCCP
IP_DCCP=n
!OFF TIPCHUB
!OFF L2TP
L2TP=n
!OFF PPP
PPP=n
!OFF SLIP
!OFF CAN
!OFF ATM
ATM=n

# ============================================================
# 针对你的场景：Headless（无本地桌面/HDMI显示）、保留 I2C/GPIO/Wi-Fi/BT/MFI 与 CarPlay 所需音视频
# 目标：去掉本地显示栈（DRM/FB/HDMI输出），保留音视频与通道驱动。
# ============================================================
DRM=n
DRM_KMS_HELPER=n
DRM_PANEL=n
DRM_BRIDGES=n
DRM_FBDEV_EMULATION=n
# DRM_FBDEV_OVERALLOC keep default (100) to avoid parsing errors when parsing integer config
DRM_DW_HDMI=n
DRM_DW_HDMI_I2S_AUDIO=n
DRM_DW_HDMI_CEC=n
DRM_SUN4I=n
DRM_SUN4I_BACKEND=n
DRM_SUN8I_MIXER=n
DRM_SUN8I_TCON_TOP=n
DRM_SUN4I_HDMI=n
DRM_SUN4I_HDMI_CEC=n
DRM_PANFROST=n
DRM_GPU_VM_MANAGEMENT=n
FB=n
FB_CORE=n
FB_DEFERRED_IO=n
VT=n
SND_SOC_HDMI_CODEC=n

# 明确保留音视频与 MFI 相关最小链路
VIDEO_SUNXI=y
VIDEO_SUNXI_CEDRUS=y
MEDIA_PLATFORM_SUPPORT=y
V4L_PLATFORM_DRIVERS=y
V4L2_MEM2MEM_DEV=y
VIDEO_V4L2_REQUESTS=y
VIDEO_V4L2_SUBDEV_API=y
MEDIA_CONTROLLER=y
V4L_TEST_DRIVERS=n
SUNXI_VE_UTILS=y

# 额外确认：GPIO/I2C/Bluetooth/Wi-Fi 必须保留
I2C=y
I2C_CHARDEV=y
GPIO_CDEV=y
GPIO_SYSFS=y
GPIOLIB=y
WIRELESS=y
WLAN=y
WLAN_VENDOR_BROADCOM=y
BRCMFMAC=y
BRCMFMAC_SDIO=y
BT=y
BT_BCM=y
BT_HCIUART=y
BT_HCIUART_BCM=y
BT_HCIUART_SERDEV=y
