from pathlib import Path
import sys
root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('/opt/zero2w-catplay-build')
p = root / 'c2a/catplay_c2a/src/media_ipc.rs'
s = p.read_text()
old = '''    fatal: AtomicBool,\n    session: AtomicU64,\n    next_stream: AtomicU32,'''
new = '''    fatal: AtomicBool,\n    /// Current active session epoch. It may be cleared during teardown.\n    session: AtomicU64,\n    /// Monotonic epoch allocator. It is deliberately independent from `session`.\n    next_session: AtomicU64,\n    next_stream: AtomicU32,'''
assert old in s
s = s.replace(old, new, 1)
old = '''            fatal: AtomicBool::new(false),\n            session: AtomicU64::new(0),\n            next_stream: AtomicU32::new(1),'''
new = '''            fatal: AtomicBool::new(false),\n            session: AtomicU64::new(0),\n            next_session: AtomicU64::new(1),\n            next_stream: AtomicU32::new(1),'''
assert s.count(old) == 2, s.count(old)
s = s.replace(old, new)
old = '''    pub fn begin_session(&self, handle: AirPlayReceiverHandleRef) {\n        let id = self.inner.session.fetch_add(1, Ordering::AcqRel) + 1;\n        *self.inner.handle.lock().unwrap() = Some(handle);\n        self.control(Control::SessionBegin(id));\n    }\n    pub fn end_session(&self, reason: u32) {\n        // Clear the active session before publishing the end marker. This makes\n        // duplicate shutdown/drop calls harmless and prevents newly-created\n        // streams from being associated with an already-ended preview session.\n        let id = self.inner.session.swap(0, Ordering::AcqRel);\n        if id != 0 {\n            self.control(Control::SessionEnd(id, reason));\n        }\n        *self.inner.handle.lock().unwrap() = None;\n    }'''
new = '''    /// Allocates a non-zero epoch without ever deriving it from the clearable\n    /// active-session slot. On integer wrap it restarts at one rather than\n    /// emitting the reserved zero epoch; practical reuse would require 2^64\n    /// completed sessions.\n    fn allocate_session_epoch(&self) -> u64 {\n        loop {\n            let observed = self.inner.next_session.load(Ordering::Acquire);\n            let epoch = if observed == 0 { 1 } else { observed };\n            let following = epoch.checked_add(1).unwrap_or(1);\n            if self\n                .inner\n                .next_session\n                .compare_exchange(observed, following, Ordering::AcqRel, Ordering::Acquire)\n                .is_ok()\n            {\n                return epoch;\n            }\n        }\n    }\n\n    pub fn begin_session(&self, handle: AirPlayReceiverHandleRef) {\n        let id = self.allocate_session_epoch();\n        *self.inner.handle.lock().unwrap() = Some(handle);\n        self.inner.session.store(id, Ordering::Release);\n        self.control(Control::SessionBegin(id));\n    }\n\n    /// Clears only the epoch this teardown observed. A delayed teardown from an\n    /// older session cannot clear a subsequently started session.\n    fn end_session_if_active(&self, id: u64, reason: u32) {\n        if id != 0\n            && self\n                .inner\n                .session\n                .compare_exchange(id, 0, Ordering::AcqRel, Ordering::Acquire)\n                .is_ok()\n        {\n            self.control(Control::SessionEnd(id, reason));\n            *self.inner.handle.lock().unwrap() = None;\n        }\n    }\n\n    pub fn end_session(&self, reason: u32) {\n        let id = self.inner.session.load(Ordering::Acquire);\n        self.end_session_if_active(id, reason);\n    }'''
assert old in s
s = s.replace(old, new, 1)
old = '''    pub(crate) fn test_begin_session(&self) {\n        let id = self.inner.session.fetch_add(1, Ordering::AcqRel) + 1;\n        self.control(Control::SessionBegin(id));\n    }'''
new = '''    pub(crate) fn test_begin_session(&self) -> u64 {\n        let id = self.allocate_session_epoch();\n        self.inner.session.store(id, Ordering::Release);\n        self.control(Control::SessionBegin(id));\n        id\n    }'''
assert old in s
s = s.replace(old, new, 1)
# `test_tap` is itself supplied by the input-only overlay, so add the allocator
# explicitly rather than relying on the base-runtime initializer replacement.
old = '''    pub(crate) fn test_tap() -> Self {\n        let (control, control_rx) = mpsc::sync_channel(CONTROL_CAP);\n        let (video, video_rx) = mpsc::sync_channel(VIDEO_CAP);\n        let (audio, audio_rx) = mpsc::sync_channel(AUDIO_CAP);\n        Self {\n            inner: Arc::new(Inner {\n                control,\n                control_rx: Mutex::new(control_rx),\n                control_count: AtomicUsize::new(0),\n                video,\n                video_rx: Mutex::new(video_rx),\n                video_count: AtomicUsize::new(0),\n                audio,\n                audio_rx: Mutex::new(audio_rx),\n                audio_count: AtomicUsize::new(0),\n                connected: AtomicBool::new(false),\n                fatal: AtomicBool::new(false),\n                session: AtomicU64::new(0),\n                next_stream: AtomicU32::new(1),'''
new = old.replace('                session: AtomicU64::new(0),\n', '                session: AtomicU64::new(0),\n                next_session: AtomicU64::new(1),\n')
assert old in s
s = s.replace(old, new, 1)
# Append focused regression inside media_ipc tests module, after all existing test definitions.
needle = '''    #[test]\n    fn malformed_annex_b_config_and_pcm_are_not_admitted() {\n        assert!(!valid_config(&[0, 0, 0, 1, 0x67]));\n        let mut pcm = AudioStreamBasicDescription::fill_pcm(48_000, 16, 16, 2, false);\n        assert!(valid_pcm(pcm));\n        pcm.bits_per_channel = 24;\n        assert!(!valid_pcm(pcm));\n    }\n}'''
addition = '''    #[test]\n    fn malformed_annex_b_config_and_pcm_are_not_admitted() {\n        assert!(!valid_config(&[0, 0, 0, 1, 0x67]));\n        let mut pcm = AudioStreamBasicDescription::fill_pcm(48_000, 16, 16, 2, false);\n        assert!(valid_pcm(pcm));\n        pcm.bits_per_channel = 24;\n        assert!(!valid_pcm(pcm));\n    }\n\n    #[test]\n    fn session_epochs_reject_stale_pcm_and_old_teardown() {\n        let inner = test_inner();\n        let tap = MediaTap { inner: inner.clone() };\n        let first = tap.test_begin_session();\n        tap.end_session(1);\n        let second = tap.test_begin_session();\n        assert_ne!(first, second);\n        assert_ne!(second, 0);\n\n        // A delayed first-session teardown must not clear the new active epoch.\n        tap.end_session_if_active(first, 2);\n        assert_eq!(tap.test_active_session(), second);\n\n        // Queue old PCM through the production drain path. It must not create\n        // an outbound record while the server has the newer active epoch.\n        let dir = TempSocketDir::new();\n        let mut server = test_server(&dir);\n        server.state.session = second;\n        server.client = Some(Client {\n            io: Box::new(ShortWriter {\n                writes: Arc::new(Mutex::new(Vec::new())),\n                amount: 1,\n                blocks: 0,\n            }),\n            pending: None,\n            queue: VecDeque::new(),\n            read: Vec::new(),\n            eagain: 0,\n        });\n        assert!(server.inner.audio.try_send(Audio {\n            session: first,\n            stream: 1,\n            sequence: 1,\n            meta: meta(),\n            samples: vec![7; 4],\n            discontinuity: false,\n        }).is_ok());\n        server.inner.audio_count.fetch_add(1, Ordering::AcqRel);\n        server.drain();\n        assert!(server.client.as_ref().unwrap().pending.is_none());\n        assert_eq!(server.inner.audio_count.load(Ordering::Acquire), 0);\n    }\n}'''
assert needle in s
s = s.replace(needle, addition, 1)
p.write_text(s)
print('updated', p)
